# Generated by Django 4.2.6 on 2023-10-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='uuid',
        ),
    ]
