# Generated by Django 4.2.6 on 2023-10-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_is_authenticated_customuser_isauthenticated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, max_length=250, upload_to='avatars'),
        ),
    ]
