# Generated by Django 4.2.6 on 2023-10-25 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_customuser_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password2',
        ),
    ]
